name: flutter_parallax
description: A Flutter widget that moves according to a scroll controller.
version: 0.1.2
author: Romain Rastel <lets4r@gmail.com>
homepage: https://github.com/letsar/flutter_parallax

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.25.7
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=3.0.0 <4.0.0"